name: Deploy to GitHub Pages
on:
  push:
    branches:
      - code

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@code
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install and predeploy scripts
        run: |
          npm install
          npm run predeploy

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:noamalffasy/noamalffasy.github.io.git
          BRANCH: master
          FOLDER: out
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
